" VIM configuration
" jachermocilla@gmail.com
"

" Enable pathogen
execute pathogen#infect()

set background=dark
set tabstop=3
set shiftwidth=3
set expandtab
set smarttab
set modeline
set wrap

autocmd FileType plugin indent on

" Filetype-specific tabs
autocmd FileType html setlocal ts=3 sw=3 expandtab
autocmd FileType javascript setlocal ts=3 sw=3 expandtab
autocmd FileType python setlocal ts=4 sw=4 expandtab

"save everytime
set autowriteall
autocmd CursorHold,CursorHoldI,InsertLeave * silent! wall

set encoding=utf8
set ffs=unix,dos,mac

set nobackup
set nowb
set noswapfile

syntax on
colorscheme torte

set number
set showmatch

"stick to 80x25
"set textwidth=75

"Key Mappings
let Tlist_WinWidth=30


"Explorer settings
"let g:netrw_banner = 0
"let g:netrw_liststyle = 3
"let g:netrw_browse_split = 4
"let g:netrw_altv = 1
"let g:netrw_winsize = 12
"augroup ProjectDrawer
"  autocmd!
"  autocmd VimEnter * :Vexplore
"  autocmd VimEnter * :execute "normal \<C-w>\<Right>"
"augroup END

" GitGutter Settings 
autocmd VimEnter * :GitGutterEnable
autocmd VimEnter * :GitGutterSignsEnable
autocmd VimEnter * :GitGutterLineHighlightsEnable
set updatetime=100

autocmd VimEnter * :WMToggle

"Generate ctags for current dir
map <F9> :!/usr/bin/ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<cr>

"make
map <F8> :!make<cr>

"make clean
map <F7> :!make clean<cr>

"git commit
map <F6> :!git commit -m'edits' % ; git push <cr>

"git push
map <F5> :!git ftp -A push <cr>

"Toggle tags list
map <F4> :TlistToggle<cr>

"Open the tags window
map <F3> :TlistOpen<cr>

"shortcut to insert license
"map <F2> :0r ~/.vim/srg-license.txt<cr>
let winManagerWindowLayout = 'FileExplorer|TagList'
map <F2> :WMToggle<cr>

