#!/usr/bin/env bash
# clone_repos.sh
# Clones repositories listed in a repo list file generated by scan_git_repos.sh
# Usage: ./clone_repos.sh [repo_list_file] [base_dir]
#
# repo_list_file : path to the TSV file (default: repos.txt)
# base_dir       : optional root to clone into (default: current directory)
#                  repos will preserve their relative paths from the scan

REPO_LIST="${1:-repos.txt}"
BASE_DIR="${2:-}"

if [ ! -f "$REPO_LIST" ]; then
  echo "Error: repo list file not found: $REPO_LIST"
  echo "Usage: $0 [repo_list_file] [base_dir]"
  exit 1
fi

echo "Repo list : $REPO_LIST"
echo "Base dir  : ${BASE_DIR:-(current directory)}"
echo ""

cloned=0
skipped=0
failed=0

while IFS=$'\t' read -r rel_path remote_url; do
  # Skip blank lines and comments
  [[ -z "$rel_path" || "$rel_path" =~ ^# ]] && continue

  # Resolve target directory
  if [ -n "$BASE_DIR" ]; then
    target_dir="${BASE_DIR}/${rel_path}"
  else
    target_dir="$rel_path"
  fi

  # Skip if already cloned
  if [ -d "$target_dir/.git" ]; then
    echo "[SKIP] Already exists: $target_dir"
    ((skipped++))
    continue
  fi

  # Create parent directories
  mkdir -p "$(dirname "$target_dir")"

  echo "[CLONE] $remote_url"
  echo "     -> $target_dir"
  if git clone "$remote_url" "$target_dir"; then
    ((cloned++))
  else
    echo "[FAIL] Could not clone: $remote_url"
    ((failed++))
  fi
  echo ""

done < "$REPO_LIST"

echo "========================================"
echo "Done."
echo "  Cloned  : $cloned"
echo "  Skipped : $skipped"
echo "  Failed  : $failed"
echo "========================================"
