#!/usr/bin/env bash
# scan_git_repos.sh
# Scans a directory for Git repositories and writes a repo list file.
# Usage: ./scan_git_repos.sh [directory] [repo_list_file]
#
# Output format (tab-separated):
#   <relative_path><TAB><remote_url>
#
# The repo list can then be passed to clone_repos.sh to recreate the structure.

SCAN_DIR="${1:-.}"
REPO_LIST="${2:-repos.txt}"

# Resolve absolute path
SCAN_DIR="$(cd "$SCAN_DIR" && pwd)"

echo "Scanning : $SCAN_DIR"
echo "Output   : $REPO_LIST"
echo ""

# Write header comment
cat > "$REPO_LIST" <<HEADER
# Git repository list — generated by scan_git_repos.sh
# Scanned from : $SCAN_DIR
# Date         : $(date)
#
# Format: <local_relative_path><TAB><remote_url>
# Lines starting with # are ignored by clone_repos.sh
HEADER

found=0
skipped=0

while IFS= read -r git_dir; do
  repo_dir="$(dirname "$git_dir")"

  # Get remote URL (prefer 'origin')
  remote_url="$(git -C "$repo_dir" remote get-url origin 2>/dev/null)"

  if [ -z "$remote_url" ]; then
    echo "[SKIP] No remote 'origin': $repo_dir"
    ((skipped++))
    continue
  fi

  # Only include GitHub remotes — remove this block to include all remotes
  if [[ "$remote_url" != *"github.com"* ]]; then
    echo "[SKIP] Not a GitHub remote ($remote_url): $repo_dir"
    ((skipped++))
    continue
  fi

  # Normalize SSH to HTTPS
  # git@github.com:user/repo.git  ->  https://github.com/user/repo.git
  if [[ "$remote_url" == git@github.com:* ]]; then
    remote_url="https://github.com/${remote_url#git@github.com:}"
  fi

  # Path relative to the scanned root
  rel_path="${repo_dir#$SCAN_DIR/}"
  if [ "$rel_path" = "$repo_dir" ] || [ -z "$rel_path" ]; then
    rel_path="$(basename "$repo_dir")"
  fi

  printf '%s\t%s\n' "$rel_path" "$remote_url" >> "$REPO_LIST"
  echo "  [FOUND] $rel_path  ->  $remote_url"
  ((found++))

done < <(find "$SCAN_DIR" -name ".git" -type d -prune 2>/dev/null | sort)

echo ""
echo "========================================"
echo "Scan complete."
echo "  Repositories found : $found"
echo "  Skipped            : $skipped"
echo "  Repo list saved    : $REPO_LIST"
echo "========================================"
echo ""
echo "To clone all repos:"
echo "  bash clone_repos.sh $REPO_LIST"
echo ""
echo "To clone into a different base directory:"
echo "  bash clone_repos.sh $REPO_LIST /path/to/new/base"
